# ===============================
# =  DATABASE CONFIGURATION     =
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/librarymngsystem
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# =  JPA / HIBERNATE SETTINGS   =
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# DDL kontrolü: tabloyu elle oluşturdun, Hibernate'e dokunma
spring.jpa.hibernate.ddl-auto=update

# SQL sorgularını konsolda göster
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Charset ayarları (isteğe bağlı)
spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'
